### ISSUE TITLE
`qeeg` here, I've changed my username on GitHub, so the README's acknowledgements section has a broken link now.

### ISSUE THREAD

**Issue by fuel-pcbox** [FWDekker/mommy#127]
Title.

**Comment by fuel-pcbox** [comment]
Also, are there any other ways to contact you privately other than email? I'd like to get to know you better, but I REALLY don't like sending emails unless I absolutely have to.

**Comment by FWDekker** [comment]
thank you for opening the issue, i was able to verify that you are indeed the same user and i've edited the readme :-)

you can contact me on discord, but i'm obviously not going to send my username here. i tried joining the pcbox discord listed in the pcbox readme to try to find you, but the invite is expired. you can send me an email with your discord username if you want, and then i can add you. if you really abhor email, you can suggest another way of connecting if you want

**Comment by fuel-pcbox** [comment]
Just emailed you my Discord username. And sorry about that, I had to lock down the PCBox discord due to trolls raiding it :/
