### ISSUE TITLE
MOMMY_SWEETIE not working in zsh

### ISSUE THREAD

**Issue by jaamivstheworld** [FWDekker/mommy#60]
I added the following:

`MOMMY_SWEETIE="boy"`

to my `.zshrc` because I would like mommy to call me a boy (oh god that sounds weird). But, of course, this isn't working. Is there another way I'm supposed to do this or does this not work in zsh?

**Comment by jaamivstheworld** [comment]
Looks like I was just putting the variable in the wrong place. Made the directory `.config/mommy` and made a file called `.config.sh` in it where I put the variable.

I should read properly next time.

**Comment by FWDekker** [comment]
that happens, no worries :-) let me know if you have any other questions, suggestions, or ideas
