### ISSUE TITLE
Error writing mommy: premision denied

### ISSUE THREAD

**Issue by artble** [FWDekker/mommy#88]
Hi, I opened mommy via nano (new computer, didnt have to make seperate directory) and changed some setings, when I wanted to save and exit "Error writing mommy: premission denied" was shown. How do I get premission?

**Comment by artble** [comment]
also it shows me that mommy is unwritable

**Comment by FWDekker** [comment]
hiya! the solution depends on a few things:

1. which operating system are you using? (windows? debian? archlinux?)
2. how did you install mommy?
3. which file exactly (the full path) are you trying to edit?

**Comment by artble** [comment]
nevermind, it is my linux issue, sth is wrong, ill get a new one on my usb
and download whole os again

pon., 1 sty 2024 o 15:34 Florine W. Dekker ***@***.***>
napisał(a):

**Comment by FWDekker** [comment]
oh, that sounds annoying. best of luck!

i'll close the issue then. if it turns out to be an issue with mommy anyway, or if you need help with anything, just leave a reply :-)
